name: Documentation
description: Report an issue with DVT documentation (README, code comments, etc.)
title: "[Docs] <title>"
labels: ["docs", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Found a typo, missing info, or confusing docs? Let us know!
  - type: textarea
    attributes:
      label: Please describe the issue and your suggestions.
      description: |
        What's wrong or missing? What would make it better?

        Tip: You can attach images by clicking this area to highlight it and then dragging files in.
    validations:
      required: true
