name: Feature Request
description: Propose a new feature or enhancement for DVT
title: "[Feature] <title>"
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We want DVT to solve real problems for data engineers, so the more context you provide, the better.
  - type: checkboxes
    attributes:
      label: Before submitting
      options:
        - label: I have searched the existing issues and could not find a match
          required: true
  - type: textarea
    attributes:
      label: Describe the feature
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: |
        A clear and concise description of any alternative solutions or workarounds you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Who will this benefit?
      description: |
        What kind of use case will this feature be useful for? Please be specific and provide examples.
    validations:
      required: false
  - type: input
    attributes:
      label: Are you interested in contributing this feature?
      description: Let us know if you want to write some code, and how we can help.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the feature you are suggesting!
    validations:
      required: false
